### ISSUE TITLE
{categories:/}{rewrite} and {categories:/}{rewrite}/ should have same page

### ISSUE THREAD

**Issue by janikjan** [ZiZuu-store/zzCleanURLs#45] opened 2016-02-09 07:20 UTC
Hi,

my actual setting for categories is:
{categories:/}{rewrite} like https://www.bezpopelniku.cz/elektronicke-cigarety/innokin

But when I tried the same link with slash at the end https://www.bezpopelniku.cz/elektronicke-cigarety/innokin/ it is not working and only show 404 page.

When I make setting for categories: {categories:/}{rewrite}/ then I have vice-versa problem.

Could you please fix this issue and make {categories:/}{rewrite} and {categories:/}{rewrite}/ to redirect to same page?
Thanks.

**Comment by ZiZuu-store** [comment] 2016-02-09 09:03
If we hardcode the requested redirect we could have conflicting URIs between products and categories, for example ..

Why having only `category/` is not enough for you? What is the real world advantage of having `category`being redirected to `category/` ?

Thank you

**Comment by janikjan** [comment] 2016-02-09 09:11
Thanks for your response. I check some ther big shops in Czech republic like mall.cz and parfums.cz

You can check it https://www.mall.cz/mobilni-telefony and https://www.mall.cz/mobilni-telefony/ are the same.

Also http://www.parfums.cz/pripravky-do-koupele/ is the same like http://www.parfums.cz/pripravky-do-koupele

I think in real world this is "normal" state. I do not think that you should have same name for category and same name for some product. At least from my point of view. For customers it is better to "fix" category without slash and also with slash I think.

**Comment by ZiZuu-store** [comment] 2016-02-09 09:21
I saw, but from a SEO point of view the category URI is the one the system knows .. if yous shop has `category/` and `category` returns a 404 there is no problem at all, as the second URI is simply a non existing URI .. no link is present in your shop that point to `category` and every link you expose is in the supported  `category/` form .. so no issue is generated nor for SEO nor for user navigation

**if** a human being deliberately removes the trailing slash he is simply requesting to your server a non-existing-page .. so 404 is the right and expected behaviour 

Giving the user the possibility of removing the trailing slash, rising a 301 (**permanently moved**) redirect gives no SEO and no usability gain IMHO ..

If you don't have other quantitative SEO or UX reasons I think this issue could be rejected ;)

**Comment by janikjan** [comment] 2016-02-09 12:49
I only want to tell you that behaviour lika I wrote is pretty normal in the world :). And i think it is better for typos by customers or some uncompleted links, etc.

You can see it also on Prestasjop original webpage like https://www.prestashop.com/forums/ and https://www.prestashop.com/forums

As you can see this is widely accepted behaviour so I think it should be better to deal with this kind of link same like the other world do it :).

**Comment by ZiZuu-store** [comment] 2016-02-09 14:45
I don't agree .. When I started using Linux the other world was using Windows :P

I'll keep this issue opened just as a reminder, in case a 0-cost implementation would arise ..

**Comment by janikjan** [comment] 2016-02-09 15:04
OK then. Thank you :).

**Comment by janikjan** [comment] 2016-02-09 20:12
Hi :).

I want to only tell you that same bahavior with or without slash at the end of category link has original Prestashop nice URLs. So I think you can make it also in this module because it seems that this is "issue" only for this module.

Please keep me updated. I also hope it will not be that hard for yout to fix it if it is working without any issues on original Prestashop URLs with IDs.

THANKS!

**Comment by ZiZuu-store** [comment] 2016-02-15 17:46
Sorry, but:
- this behaviour is not a bug
- no SEO issues are raised by this behaviour
- implementing it in a consistent way is quite impossible
- implementing a 301 redirect is over the scope of this module (it has to remove ID from the URL)
- **301** is not the only solution, implementing **canonical** is another option. This module can't decide for the user
- the "fix" is not trivial and there is a risk to introduce bugs, having a negligible counterpart.

**Comment by ZiZuu-store** [comment] 2016-02-15 17:49
Sorry, but:
- this behaviour is not a bug
- no SEO issues are raised by this behaviour
- implementing a 301 redirect is over the scope of this module (it has to remove ID from the URL)
- **301** is not the only solution, implementing **canonical** is another option. This module can't decide for the user
- the "fix" is not trivial and there is a risk to introduce bugs, having a negligible counterpart.
- introducing too much logic in the Dispatcher makes it run **slower** .. and it is invoked every time you request a new page!

For all these reasons I'm going to reject this RFE and close this issue.

Hope you can live without it too ;)

**Closed by ZiZuu-store** 2016-02-15 17:49 UTC
Labels: enhancement

**Comment by janikjan** [comment] 2016-02-15 17:57
OK, what should I do :). The most important point is another issue which you knwo about it :).

**Comment by ZiZuu-store** [comment] 2016-02-15 17:58
:+1:
