### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by mantasl** [ZiZuu-store/zzCleanURLs#15] opened 2015-09-19 18:41 UTC
Hey, have you checked pagination? I found an issue when using this clean url module pagination is wrong. For example, im in A category where I could see: 34 products. Default pagination - 12 products/page. On second page I see only 11 products and on 3rd page - i can open it but nothing here. Any solution?

**Comment by ZiZuu-store** [comment] 2015-09-19 21:30
What version of PS, whar bersion of the module, any other info?

Of course pagination should habe nothing to do with id removal .. so plz
provide more info in orther to argue what is the problem in your scenario


Il sabato 19 settembre 2015, mantasl <notifications@github.com> ha scritto:

> Hey, have you checked pagination? I found an issue when using this clean
> url module pagination is wrong. For example, im in A category where I could
> see: 34 products. Default pagination - 12 products/page. On second page I
> see only 11 products and on 3rd page - i can open it but nothing here. Any
> solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZiZuu-store/zzCleanURLs/issues/15>.
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by ZiZuu-store** [comment] 2015-09-20 09:30
Plz tell me a real world URL I can inspect too

**Comment by mantasl** [comment] 2015-09-20 09:43
Hey, man,

sorry, I could answer you right now.

Module version: latest. I have reuploaded all files a day ago.

Check this live URL: http://imuperku.lt/auto/aksesuarai-ir-priedai/?p=2

Sorry for language. But you can see that in this category 34 products. But
in second page I can see only 11 products. Sum = 23 products and 3rd page -
blank.

Thanks for any help man!





2015-09-20 12:30 GMT+03:00 ZiZuu.com <notifications@github.com>:

**Comment by ZiZuu-store** [comment] 2015-09-20 09:47
What you mean with latest?
Downloaded the zip from github?

Plz gimme your PS version and any other meaningful info

Tnx

**Comment by mantasl** [comment] 2015-09-20 09:48
Latest: yes I downloaded all files and reuploaded to override folder. Old
files replacted to new.

My PS version: 1.6.14

What other information do you need? I gave you url with example, could you
check this? What other information could I give you?



2015-09-20 12:47 GMT+03:00 ZiZuu.com <notifications@github.com>:

**Comment by ZiZuu-store** [comment] 2015-09-22 10:46
What theme are you using? .. pagination should be handled by the theme .. 

Can't argue how ID removal could apply .. btw, I'm going to take a look to your link

**Comment by ZiZuu-store** [comment] 2015-09-22 10:52
Pagination seems not to be the root problem in your site:
http://imuperku.lt/auto/aksesuarai-ir-priedai/?id_category=87&n=34  -> only 23 products displayed

http://imuperku.lt/auto/aksesuarai-ir-priedai/?id_category=87&n=60  -> 23 products displayed even if 60 per page is selected ..

AFAICS my module should have nothing to do with this behaviour ...

Removing it makes other products appear? .. please let me see :)

**Comment by ZiZuu-store** [comment] 2015-09-23 21:18
@mantasl plz try the new release ..

Going to close if no news ..

**Comment by mantasl** [comment] 2015-09-24 07:08
Hey, ZiZu,

after classess override Link n dispatcher I got 404 error when I visit
category page.

I reuploaded a new files from GitHub.

2015-09-24 0:18 GMT+03:00 ZiZuu.com <notifications@github.com>:

**Comment by ZiZuu-store** [comment] 2015-09-24 07:44
I don't understand .. please join me on chat at https://gitter.im/ZiZuu-store/zzCleanURLs

**Comment by ZiZuu-store** [comment] 2015-10-01 21:10
No feedback given ... Can't reproduce 

Closing

**Closed by ZiZuu-store** 2015-10-01 21:10 UTC
Labels: feedback
