### ISSUE TITLE
Fatal error under installation

### ISSUE THREAD

**Issue by jeppeskovbakke** [ZiZuu-store/zzCleanURLs#23] opened 2015-11-16 08:21 UTC
Downloaded v.1.0.1. Uploaded to PS 1.6.0.14 and get this message after clicking 'Install'
 
[PrestaShop] Fatal error in module file :/home/primates/public_html/modules/zzcleanurls/zzcleanurls.php:
Call to undefined method zzCleanUrls::displayWarning()

**Comment by ZiZuu-store** [comment] 2015-11-16 08:24
Hi @jeppeskovbakke,
  I'm investigating .. stay tuned

**Comment by ZiZuu-store** [comment] 2015-11-16 08:25
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2ue9EJj0&#x2F;13-fatal-error-on-install"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Fatal error on install</a>

**Comment by ZiZuu-store** [comment] 2015-11-16 08:38
@jeppeskovbakke the function is a method of the PS core Module class (see https://github.com/PrestaShop/PrestaShop/blob/develop/classes/module/Module.php#L2110)

I can't reproduce your issue .. please double check if you have any oder override module .. then verify the content of the file `<YOUR_PS_ROOT>/override/classes/module/Module.php` .. 

Please paste here the contents of this file .. 

I'm sure at 99,99% this should not be a zzCleanURLs issue .. but please help me to investigate deeper

Thank you

**Comment by jeppeskovbakke** [comment] 2015-11-16 09:08
Thanks for investigating!
I have nothing but index.php in override/classes/module/
I have been using another URL cleaner earlier on -Clean URLs by ha!*!*y.
It's uninstalled but could there be some remains leading to this issue?
KR Jeppe

man. 16. nov. 2015 09.38 skrev ZiZuu.com <notifications@github.com>:

**Comment by ZiZuu-store** [comment] 2015-11-16 09:25
Yes maybe ..

If you do not use any other overriding module please:

- uninstall my module
- remove my module from the disk
- remove any file in the `PS_ROOT/overrides/` tree, except for index.php files ..
- then clear any cache ..
- disable/re-enable URLs and SEO -> SEO friendly URLs
- double check the PS overrides dir is empty (except the dir structure and the index.php files
- double check the `PS/modules/` dir does not contains any "strange" dir/file (`__MacOSX` dir, temporary files .. etc)
- check `PS/modules/` permissions

Then install the module again

**Comment by jeppeskovbakke** [comment] 2015-11-16 12:38
Sorry was just out of the house for a while...
Followed the instructions as closely as possible, -mind you I do have some overrides in classes and controllers, just not in modules. Permissions are fine.
It still throws the same fatal error on installation.

**Comment by jeppeskovbakke** [comment] 2015-11-16 12:43
Your overrides are in /classes/controller/frontcontroller.php and /controllers/front/* right?
The ones I have are all related to pdf generation, so there should be no conflicts

**Comment by jeppeskovbakke** [comment] 2015-11-16 13:07
Looked at a backup and found that they're the same files that used to be overridden by cleanURLs, but nothing seems to have been left behind as these folders are empty after uninstalling your module.

**Comment by ZiZuu-store** [comment] 2015-11-25 22:42
@jeppeskovbakke I can't reproduce ..

**Comment by ZiZuu-store** [comment] 2015-11-30 16:47
Sorry but I can't find a way to rise your issue .. I'm closing this issue .. if you will have more info feel free to reopen it

Thank you

**Closed by ZiZuu-store** 2015-11-30 16:47 UTC
Labels: assigned, bug, feedback, working
